"use strict";
(() => {
  const FIELDS=["clientRecordId","createdAt","updatedAt","decision","status","category","displayLabel","source","analysisMode","syncStatus","syncAttempts","lastSyncErrorCode","serverRecordId","syncedAt","resolvedAt"];
  const safeCode=value=>value===403||String(value||"").includes("403")?"app-check-permission-denied":String(value||"sync-failed").replace(/[^a-z0-9-]/gi,"-").slice(0,80);
  const id=()=>globalThis.crypto?.randomUUID?.()||`local-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,12)}`;
  const clean=(input,existing={})=>{const now=new Date().toISOString(),value={...existing}; for(const key of FIELDS)if(key in input)value[key]=input[key]; value.clientRecordId=value.clientRecordId||id();value.createdAt=existing.createdAt||value.createdAt||now;value.updatedAt=now;value.decision=value.decision==="held"?"held":"completed";value.status=["completed","held","resolved"].includes(value.status)?value.status:value.decision;value.syncStatus=existing.syncStatus==="synced"&&input.syncStatus==="pending"?"synced":["pending","syncing","synced","failed"].includes(value.syncStatus)?value.syncStatus:"pending";value.syncAttempts=Number(value.syncAttempts)||0;for(const key of ["lastSyncErrorCode","serverRecordId","syncedAt","resolvedAt"])value[key]=value[key]??null;return Object.fromEntries(FIELDS.map(key=>[key,value[key]]));};
  const memory=()=>{const map=new Map();return {async get(key){return map.get(key)||null},async put(value){map.set(value.clientRecordId,value);return value},async all(){return [...map.values()]},async del(key){map.delete(key)},async clear(){map.clear()}}};
  const indexed=()=>{let db;const open=()=>new Promise((resolve,reject)=>{if(db)return resolve(db);const r=indexedDB.open("aiways-sorting",1);r.onupgradeneeded=()=>{const s=r.result.createObjectStore("records",{keyPath:"clientRecordId"});s.createIndex("syncStatus","syncStatus");s.createIndex("createdAt","createdAt");s.createIndex("status","status")};r.onsuccess=()=>resolve(db=r.result);r.onerror=()=>reject(r.error)});const run=(mode,fn)=>open().then(database=>new Promise((resolve,reject)=>{const tx=database.transaction("records",mode),s=tx.objectStore("records");let out;try{out=fn(s)}catch(error){reject(error);return}tx.oncomplete=()=>resolve(out);tx.onerror=()=>reject(tx.error)}));return {get:key=>run("readonly",s=>new Promise((resolve,reject)=>{const r=s.get(key);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})),put:value=>run("readwrite",s=>s.put(value)),all:()=>run("readonly",s=>new Promise((resolve,reject)=>{const r=s.getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})),del:key=>run("readwrite",s=>s.delete(key)),clear:()=>run("readwrite",s=>s.clear())}};
  const create=(adapter=(typeof indexedDB!=="undefined"?indexed():memory()))=>{const store={openSortingDb:async()=>adapter,async saveLocalSortingRecord(input){const old=await adapter.get(input.clientRecordId);const record=clean(input,old||{});await adapter.put(record);return record},getLocalSortingRecord:key=>adapter.get(key),async listLocalSortingRecords(){return (await adapter.all()).sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt)))},async listPendingSortingRecords(){return (await store.listLocalSortingRecords()).filter(r=>r.syncStatus==="pending"||r.syncStatus==="failed")},async updateLocalSortingRecord(key,patch){const old=await adapter.get(key);if(!old)throw new Error("record-not-found");const record=clean({...old,...patch},old);await adapter.put(record);return record},deleteLocalSortingRecord:key=>adapter.del(key),clearLocalSortingRecords:()=>adapter.clear(),async resolveLocalHeldRecord(key,patch={}){const old=await adapter.get(key);if(!old||old.status!=="held")throw new Error("held-record-not-found");const record=clean({...old,...patch,status:"resolved",resolvedAt:new Date().toISOString(),syncStatus:"pending"},{...old,syncStatus:"pending"});await adapter.put(record);return record},async syncPendingSortingRecords(syncOne){const rows=await store.listPendingSortingRecords(),out=[];for(const row of rows){const syncing=await store.updateLocalSortingRecord(row.clientRecordId,{syncStatus:"syncing",syncAttempts:row.syncAttempts+1});try{const result=await syncOne(syncing);out.push(await store.updateLocalSortingRecord(row.clientRecordId,{syncStatus:"synced",serverRecordId:result?.serverRecordId||null,syncedAt:new Date().toISOString(),lastSyncErrorCode:null}))}catch(error){out.push(await store.updateLocalSortingRecord(row.clientRecordId,{syncStatus:"failed",lastSyncErrorCode:safeCode(error?.status||error?.code)}))}}return out}};return store};
  const csv=records=>{const header=["clientRecordId","createdAt","decision","status","category","displayLabel","source","analysisMode","syncStatus","syncedAt","resolvedAt"],seen=new Set(),quote=value=>{let text=String(value??"");if(/^[=+\-@]/.test(text))text="'"+text;return `"${text.replace(/"/g,'""')}"`};return "\uFEFF"+header.join(",")+"\r\n"+[...records].sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt))).filter(r=>!seen.has(r.clientRecordId)&&seen.add(r.clientRecordId)).map(r=>header.map(k=>quote(r[k])).join(",")).join("\r\n")};
  const api={createSortingLocalStore:create,buildSortingRecordsCsv:csv,downloadSortingRecordsCsv(records,now=new Date()){const stamp=now.toISOString().replace(/[-:]/g,"").replace(/T/,"-").slice(0,13);const blob=new Blob([csv(records)],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`aiways-sorting-records-${stamp}.csv`;a.click();URL.revokeObjectURL(url)}};if(typeof module!=="undefined")module.exports=api;else globalThis.AIWaysSortingLocalStore=api;
})();
