"use strict";
const assert=require("node:assert/strict");
const {getApps,initializeApp}=require("firebase-admin/app"); const {getFirestore}=require("firebase-admin/firestore");
const {createAnalysisIdempotency,hashIdempotencyKey}=require("../lib/analysisIdempotency"); const {createGlobalRateLimiter}=require("../lib/globalRateLimit"); const {createAnalyzeSortingHandler}=require("../lib/sortingVision");
if(!getApps().length)initializeApp({projectId:"demo-aiways-incheon"}); const db=getFirestore();
const imageData="iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADElEQVR42mNk+M/wHwAF/gL+QKQe2QAAAABJRU5ErkJggg==";
function body(key,requestId){return{schemaVersion:"sorting-vision-v1",requestId,sessionId:"emulator-session",idempotencyKey:key,locale:"ko-KR",source:"future_gemini",image:{mimeType:"image/png",data:imageData},imageMetadata:{mimeType:"image/png",width:1,height:1,byteLength:70},userContext:{}};}
async function call(handler,payload){const out={};const res={set(k,v){out.headers??={};out.headers[k]=v;return this},status(v){out.status=v;return this},json(v){out.body=v;return this},send(v){out.body=v;return this}};await handler({method:"POST",headers:{},body:payload},res);return out;}
async function main(){let providerCalls=0;let release;const gate=new Promise(resolve=>release=resolve);const requests=createAnalysisIdempotency({db,model:"gemini-3.5-flash-lite"});const limiter=createGlobalRateLimiter({db});const response=id=>({text:JSON.stringify({schemaVersion:"sorting-vision-v1",requestId:id,provider:"future_gemini",objectCandidates:[],materialCandidates:[],visibleCautions:[],uncertainty:"high",needsUserCheck:true})});const handler=createAnalyzeSortingHandler({getApiKey:()=>"mock",analysisRequests:requests,rateLimiter:limiter,logRateLimit:()=>{},createClient:()=>({models:{generateContent:async()=>{providerCalls++;await gate;return response("concurrent-request");}}})});
const concurrentKey="123e4567-e89b-42d3-a456-426614174001";const first=call(handler,body(concurrentKey,"concurrent-request"));await new Promise(resolve=>setTimeout(resolve,30));const second=await call(handler,body(concurrentKey,"concurrent-request"));assert.equal(second.status,409);release();assert.equal((await first).status,200);assert.equal(providerCalls,1);const before=(await db.doc(`system_rate_limits/analyzeSortingImage-${new Date().toISOString().slice(0,10).replace(/-/g,"")}`).get()).data().totalCount;const cached=await call(handler,body(concurrentKey,"concurrent-request"));assert.equal(cached.status,200);assert.equal(providerCalls,1);const after=(await db.doc(`system_rate_limits/analyzeSortingImage-${new Date().toISOString().slice(0,10).replace(/-/g,"")}`).get()).data().totalCount;assert.equal(after,before);
const failedKey="123e4567-e89b-42d3-a456-426614174002";const failedHandler=createAnalyzeSortingHandler({getApiKey:()=>"mock",analysisRequests:requests,rateLimiter:limiter,logRateLimit:()=>{},createClient:()=>({models:{generateContent:async()=>{providerCalls++;throw new Error("mock failure");}}})});assert.equal((await call(failedHandler,body(failedKey,"failed-request"))).status,502);const failedCalls=providerCalls;assert.equal((await call(failedHandler,body(failedKey,"failed-request"))).status,502);assert.equal(providerCalls,failedCalls);const doc=(await db.doc(`system_analysis_requests/${hashIdempotencyKey(concurrentKey)}`).get()).data();assert.equal(doc.state,"completed");assert.equal(doc.provider,"future_gemini");assert.equal(doc.model,"gemini-3.5-flash-lite");assert.equal(doc.expireAt.toDate().getTime()-doc.createdAt.toDate().getTime(),600000);assert.equal(doc.processingExpiresAt.toDate().getTime()-doc.createdAt.toDate().getTime(),60000);const text=JSON.stringify(doc);for(const forbidden of ["idempotencyKey","base64","sessionId","prompt","authorization","apiKey"])assert.equal(text.toLowerCase().includes(forbidden.toLowerCase()),false);process.stdout.write("Analysis idempotency emulator smoke test passed\n");}
main().catch(error=>{console.error(error);process.exitCode=1;});
