"use strict";
const crypto = require("node:crypto"), fs = require("node:fs"), http = require("node:http"), os = require("node:os"), path = require("node:path"), WebSocket = require("ws");
const output = path.join(os.tmpdir(), `aiways-cb3-${Date.now()}`); fs.mkdirSync(output, { recursive: true });
function request(pathname, method = "GET") { return new Promise((resolve, reject) => { const req = http.request({ hostname: "127.0.0.1", port: 9239, path: pathname, method }, res => { let body = ""; res.on("data", data => body += data); res.on("end", () => resolve(JSON.parse(body))); }); req.on("error", reject); req.end(); }); }
function connect(url) { return new Promise((resolve, reject) => { const socket = new WebSocket(url); let id = 0; const pending = new Map(), events = []; socket.on("open", () => resolve({ events, send(method, params = {}) { return new Promise((done, fail) => { const messageId = ++id; pending.set(messageId, { done, fail }); socket.send(JSON.stringify({ id: messageId, method, params })); }); }, close: () => socket.close() })); socket.on("message", message => { const packet = JSON.parse(message); if (packet.id && pending.has(packet.id)) { const item = pending.get(packet.id); pending.delete(packet.id); return packet.error ? item.fail(packet.error) : item.done(packet.result); } if (["Runtime.exceptionThrown", "Log.entryAdded"].includes(packet.method)) events.push(packet); }); socket.on("error", reject); }); }
async function value(page, expression) { return (await page.send("Runtime.evaluate", { expression, returnByValue: true, awaitPromise: true })).result.value; }
async function shot(page, name, selector) { await value(page, `document.querySelector(${JSON.stringify(selector)})?.scrollIntoView({block:'start'});`); await new Promise(resolve => setTimeout(resolve, 120)); const data = await page.send("Page.captureScreenshot", { format: "png", captureBeyondViewport: false }); fs.writeFileSync(path.join(output, `${name}.png`), Buffer.from(data.data, "base64")); }
(async () => { const target = await request(`/json/new?${encodeURIComponent("http://127.0.0.1:8001/")}`, "PUT"), page = await connect(target.webSocketDebuggerUrl); await page.send("Page.enable"); await page.send("Runtime.enable"); await page.send("Log.enable"); const captures = [];
  for (const [width, height] of [[390,844],[768,1024],[1024,768],[1366,768],[1920,1080]]) { await page.send("Emulation.setDeviceMetricsOverride", { width, height, deviceScaleFactor: 1, mobile: width <= 430 }); await page.send("Page.navigate", { url: "http://127.0.0.1:8001/" }); await new Promise(resolve => setTimeout(resolve, 500)); const label = `${width}x${height}`; await shot(page, `dashboard-${label}`, "#dashboard"); captures.push(`dashboard-${label}.png`); if (width === 1366) for (const section of ["project","curriculum","hah","flow","gallery","sorting","resources"]) { await shot(page, section, `#${section}`); captures.push(`${section}.png`); } }
  await value(page, `document.querySelector('[data-sorting-mode="quick"]')?.click();document.querySelector('[data-quick-item="milk"]')?.click();`); await shot(page, "sorting-result", "[data-sorting-result]"); captures.push("sorting-result.png"); await value(page, `document.querySelector('#practiceLogButton')?.click();`); await shot(page, "sorting-completed", "[data-sorting-result]"); captures.push("sorting-completed.png"); await value(page, `document.querySelector('#holdLogButton')?.click();document.querySelector('[data-tab="holds"]')?.click();`); await shot(page, "sorting-held", "#holdList"); captures.push("sorting-held.png"); await value(page, `document.querySelector('.edu2g-beta-trigger')?.click();`); await shot(page, "edu2g-dialog", ".edu2g-beta-dialog"); captures.push("edu2g-dialog.png"); await page.send("Page.navigate", { url: "http://127.0.0.1:8001/?visual-tuner=1" }); await new Promise(resolve => setTimeout(resolve, 250)); await shot(page, "visual-tuner", ".visual-tuner"); captures.push("visual-tuner.png");
  const manifest = Object.fromEntries(captures.map(file => [file, crypto.createHash("sha256").update(fs.readFileSync(path.join(output, file))).digest("hex")])); fs.writeFileSync(path.join(output, "sha256-manifest.json"), JSON.stringify(manifest, null, 2)); const viewport = await value(page, `({overflow:document.documentElement.scrollWidth===document.documentElement.clientWidth&&document.body.scrollWidth===document.documentElement.clientWidth})`); page.close(); if (!viewport.overflow || page.events.length) throw new Error("CB-3 capture contract failed"); process.stdout.write(JSON.stringify({ output, captures: captures.length, consoleErrors: 0, overflow: 0 }) + "\n");
})().catch(error => { process.stderr.write(`${error.message}\n`); process.exitCode = 1; });
