"use strict";
const assert = require("node:assert/strict"), fs = require("node:fs"), path = require("node:path"), test = require("node:test"), vm = require("node:vm");
const root = path.resolve(__dirname, "..", ".."), html = fs.readFileSync(path.join(root, "index.html"), "utf8"), clientSource = fs.readFileSync(path.join(root, "edu2gBetaClient.js"), "utf8"), uiSource = fs.readFileSync(path.join(root, "edu2gBetaUi.js"), "utf8");
function clientHarness({ fetchImpl, hostname = "localhost", search = "?auth-emulator=1", visualReview = false } = {}) { const location = { hostname, search }, window = { AIWaysAppCheck: { initializeAIWaysAppCheck: async () => ({ app: { options: { projectId: "ai-ways-incheon" } } }) }, AIWaysBetaAuth: { visualReviewRequested: () => visualReview, getEdu2gProtectedHeaders: async ({ forceRefresh } = {}) => ({ "X-Firebase-AppCheck": "app-check", Authorization: `Bearer token-${forceRefresh ? "fresh" : "cached"}` }) } }; vm.runInNewContext(clientSource, { window, location, navigator: { platform: "Win32" }, URLSearchParams, AbortController, fetch: fetchImpl, setTimeout, clearTimeout }, { filename: "edu2gBetaClient.js" }); return window.AIWaysEdu2gClient; }
test("Gate 2A scripts are ordered and preserve the original eight navigation links", () => { const order = ["./firebaseAppCheck.js", "./firebaseBetaAuth.js", "./edu2gBetaClient.js", "./edu2gBetaUi.js", "./aiRuntimeLoader.js", "./app.js"].map(value => html.indexOf(value)); assert.ok(order.every((value, index) => value >= 0 && (!index || order[index - 1] < value))); assert.equal((html.match(/<nav class="main-nav"[\s\S]*?<\/nav>/)?.[0].match(/<a href=/g) || []).length, 8); assert.match(html, /edu2gBeta\.css/); });
test("Gate 2A client allowlists protected endpoints and selects production or explicit localhost emulator URLs", async () => { const client = clientHarness({ fetchImpl: async () => ({ status: 200, json: async () => ({ ok: true }) }) }); assert.equal(await client.functionUrl("getEdu2gSession"), "http://127.0.0.1:5001/demo-aiways-incheon/asia-northeast3/getEdu2gSession"); assert.equal(await client.functionUrl("analyzeSortingImage"), "http://127.0.0.1:5001/demo-aiways-incheon/asia-northeast3/analyzeSortingImage"); await assert.rejects(() => client.functionUrl("unknownEndpoint"), /endpoint_not_allowed/); const production = clientHarness({ hostname: "example.test", search: "?auth-emulator=1", fetchImpl: async () => ({ status: 200, json: async () => ({ ok: true }) }) }); assert.equal(await production.functionUrl("saveSortingRecord"), "https://asia-northeast3-ai-ways-incheon.cloudfunctions.net/saveSortingRecord"); });

test("CB-4 protected analyze and record helpers send no client actor identifier", async () => { const requests = []; const client = clientHarness({ fetchImpl: async (_url, options) => { requests.push(JSON.parse(options.body)); return { status: 200, json: async () => ({ ok: true }) }; } }); await client.analyzeSortingImage({ requestId: "request-1" }); await client.saveSortingRecord({ status: "held" }); assert.equal(requests.length, 2); assert.equal(Object.hasOwn(requests[0], "actorId"), false); assert.equal(Object.hasOwn(requests[1], "actorId"), false); });
test("Gate 2A client sends protected JSON headers and retries a 401 once with a refreshed token", async () => { const calls = [], client = clientHarness({ fetchImpl: async (_url, options) => { calls.push(options); return calls.length === 1 ? { status: 401, json: async () => ({ ok: false, code: "auth_invalid" }) } : { status: 200, json: async () => ({ ok: true, displayName: "beta" }) }; } }); const result = await client.getSession(); assert.equal(result.ok, true); assert.equal(calls.length, 2); assert.equal(calls[0].credentials, "omit"); assert.equal(calls[0].headers["Content-Type"], "application/json"); assert.equal(calls[0].headers.Authorization, "Bearer token-cached"); assert.equal(calls[1].headers.Authorization, "Bearer token-fresh"); });
test("explicit visual review mode returns before protected headers or network", async () => { const calls = []; const client = clientHarness({ visualReview: true, fetchImpl: async () => { calls.push("fetch"); return { status: 200, json: async () => ({ ok: true }) }; } }); assert.equal((await client.getSession()).code, "auth_invalid"); assert.equal(calls.length, 0); });
test("Gate 2A client maps malformed, network and timeout responses without exposing bodies", async () => { const malformed = clientHarness({ fetchImpl: async () => ({ status: 200, json: async () => { throw new Error("bad json"); } }) }); assert.equal((await malformed.getSession()).code, "invalid_response"); const network = clientHarness({ fetchImpl: async () => { throw new Error("offline"); } }); assert.equal((await network.getSession()).code, "network_error"); const timeout = clientHarness({ fetchImpl: async () => { const error = new Error("aborted"); error.name = "AbortError"; throw error; } }); assert.equal((await timeout.getSession()).code, "request_timeout"); });
test("Gate 2A UI protects PASS and identity details while using namespaced, safe DOM construction", () => { for (const source of [clientSource, uiSource]) assert.doesNotMatch(source, /console\.|localStorage|sessionStorage|innerHTML|actorId|\.uid|idToken/); assert.match(uiSource, /textContent/); assert.match(uiSource, /showModal\(\)/); assert.match(uiSource, /clearEdu2gDeviceSession/); assert.match(uiSource, /autocomplete = "one-time-code"/); assert.match(uiSource, /label\.value\.trim\(\)/); assert.match(uiSource, /confirm\(/); assert.match(uiSource, /aria-live/); assert.match(uiSource, /edu2g-beta-/); });
