"use strict";

// Browser-only Gate 2A smoke. It creates an in-memory page and supplies a
// client mock, so it cannot contact Firebase, Functions, Firestore, or Gemini.
const fs = require("node:fs");
const http = require("node:http");
const path = require("node:path");
const WebSocket = require("ws");
const root = path.resolve(__dirname, "..", "..");
const style = fs.readFileSync(path.join(root, "style.css"), "utf8") + fs.readFileSync(path.join(root, "edu2gBeta.css"), "utf8");
const ui = fs.readFileSync(path.join(root, "edu2gBetaUi.js"), "utf8");
const viewports = [[320, 568], [390, 844], [768, 1024], [1366, 768], [1920, 1080]];
function request(pathname, method = "GET") { return new Promise((resolve, reject) => { const req = http.request({ hostname: "127.0.0.1", port: 9239, path: pathname, method }, res => { let body = ""; res.on("data", chunk => body += chunk); res.on("end", () => resolve(JSON.parse(body))); }); req.on("error", reject); req.end(); }); }
function connect(url) { return new Promise((resolve, reject) => { const socket = new WebSocket(url); let id = 0; const pending = new Map(), events = []; socket.on("open", () => resolve({ events, send(method, params = {}) { return new Promise((done, fail) => { const messageId = ++id; pending.set(messageId, { done, fail }); socket.send(JSON.stringify({ id: messageId, method, params })); }); }, close: () => socket.close() })); socket.on("message", message => { const packet = JSON.parse(message); if (packet.id && pending.has(packet.id)) { const item = pending.get(packet.id); pending.delete(packet.id); return packet.error ? item.fail(packet.error) : item.done(packet.result); } if (["Runtime.exceptionThrown", "Log.entryAdded", "Network.requestWillBeSent"].includes(packet.method)) events.push(packet); }); socket.on("error", reject); }); }
async function evaluate(page, expression) { return (await page.send("Runtime.evaluate", { expression, returnByValue: true, awaitPromise: true })).result.value; }
const pageHtml = `<html><head><style>${style.replace(/<\/style/gi, "")}</style></head><body><header class="site-header"><a class="brand" href="#dashboard">AI Ways Incheon</a><nav class="main-nav"><a href="#dashboard">대시보드</a></nav></header></body></html>`;
(async () => {
  const target = await request(`/json/new?${encodeURIComponent(`data:text/html,${encodeURIComponent(pageHtml)}`)}`, "PUT");
  const page = await connect(target.webSocketDebuggerUrl); await page.send("Page.enable"); await page.send("Runtime.enable"); await page.send("Log.enable"); await page.send("Network.enable");
  await evaluate(page, `window.__gate2a={cleared:0,lists:0};window.confirm=()=>true;window.AIWaysEdu2gClient={getSession:async()=>({ok:false,code:'device_not_registered'}),errorMessageFor:()=> '연결을 확인해 주세요.',getPlatformLabel:()=> 'Windows',requestAccess:async()=>({ok:true,data:{displayName:'베타 사용자',deviceLabel:'현재 기기',activeDeviceCount:3,maxDevices:5,requiresDeviceConfirmation:true}}),confirmDeviceRegistration:async()=>({ok:true,data:{displayName:'베타 사용자',deviceLabel:'현재 기기',activeDeviceCount:3,maxDevices:5}}),listTrustedDevices:async()=>{window.__gate2a.lists++;return {ok:true,data:{devices:[{managementId:'m1',deviceLabel:'현재 기기',platform:'Windows',currentDevice:true,status:'active'},{managementId:'m2',deviceLabel:'다른 기기 1',platform:'Android',currentDevice:false,status:'active'},{managementId:'m3',deviceLabel:'다른 기기 2',platform:'macOS',currentDevice:false,status:'active'}]}}},revokeTrustedDevice:async()=>({ok:true,data:{}})};window.AIWaysBetaAuth={clearEdu2gDeviceSession:async()=>{window.__gate2a.cleared++}};`);
  await evaluate(page, `${ui}\nwindow.dispatchEvent(new Event('DOMContentLoaded'));`);
  const rows = [];
  for (const [width, height] of viewports) {
    await page.send("Emulation.setDeviceMetricsOverride", { width, height, deviceScaleFactor: 1, mobile: width <= 390 });
    rows.push({ width, height, ...(await evaluate(page, `(() => { const trigger=document.querySelector('.edu2g-beta-trigger'); trigger.click(); const dialog=document.querySelector('.edu2g-beta-dialog'); const login=document.querySelector('input[name="edu2g-login"]'); const r=dialog.getBoundingClientRect(); dialog.close(); return {trigger:Boolean(trigger), dialog:Boolean(dialog?.open===false), login:Boolean(login&&login.type==='text'), overflow:document.documentElement.scrollWidth===document.documentElement.clientWidth&&document.body.scrollWidth===document.documentElement.clientWidth, touch:trigger?.getBoundingClientRect().height>=44, dialogWidth:r.width, viewport:innerWidth}; })()`)) });
  }
  const flow = await evaluate(page, `(async()=>{try{const wait=()=>new Promise(resolve=>setTimeout(resolve,20));const trigger=document.querySelector('.edu2g-beta-trigger');trigger.click();let form=document.querySelector('.edu2g-beta-form');if(!form)throw new Error('form');form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));const invalid=Boolean(document.querySelector('.edu2g-beta-message'));const login=document.querySelector('input[name="edu2g-login"]');if(!login)throw new Error('login');login.value='beta user';form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await wait();const confirm=[...document.querySelectorAll('.edu2g-beta-dialog button')].find(button=>button.textContent==='등록');if(!confirm)throw new Error('confirm');confirm.click();await wait();const registered=Boolean(document.querySelector('.edu2g-beta-session'));const manage=document.querySelector('.edu2g-beta-session button');if(!manage)throw new Error('manage');manage.click();await wait();const devices=document.querySelectorAll('.edu2g-beta-device').length;const other=[...document.querySelectorAll('.edu2g-beta-device button')].find(button=>button.textContent==='기기 해제');if(!other)throw new Error('other');other.click();await wait();const retained=Boolean(document.querySelector('.edu2g-beta-session'));const current=[...document.querySelectorAll('.edu2g-beta-device button')].find(button=>button.textContent==='이 기기 해제');if(!current)throw new Error('current');current.click();await wait();return {invalid,registered,devices,retained,cleared:window.__gate2a.cleared,unregistered:Boolean(document.querySelector('input[name="edu2g-login"]')),lists:window.__gate2a.lists};}catch(error){return {error:String(error)}}})()`);
  await page.send("Emulation.setPageScaleFactor", { pageScaleFactor: 2 }); const zoom = await evaluate(page, `({overflow:document.documentElement.scrollWidth===document.documentElement.clientWidth&&document.body.scrollWidth===document.documentElement.clientWidth})`); await page.send("Emulation.setPageScaleFactor", { pageScaleFactor: 1 });
  const firebaseRequests = page.events.filter(event => event.method === "Network.requestWillBeSent" && /firebase|cloudfunctions|googleapis/i.test(event.params?.request?.url || "")); page.close(); const bad = rows.find(row => !row.trigger || !row.dialog || !row.login || !row.overflow || !row.touch || row.dialogWidth > row.viewport);
  if (bad) throw new Error(`Gate 2A browser smoke failed: ${JSON.stringify(bad)}`); if (flow?.error || !flow?.invalid || !flow?.registered || flow.devices !== 3 || !flow.retained || flow.cleared !== 1 || !flow.unregistered || flow.lists < 2 || !zoom.overflow) throw new Error(`Gate 2A browser flow failed: ${JSON.stringify(flow)}`); if (firebaseRequests.length) throw new Error("Gate 2A browser smoke made an external request"); if (page.events.some(event => event.method !== "Network.requestWillBeSent")) throw new Error("Gate 2A browser console failure");
  process.stdout.write(JSON.stringify({ gate2aBrowser: "passed", viewports: rows.length, externalRequests: 0, flow, zoom }) + "\n");
})().catch(error => { process.stderr.write(`${error.message}\n`); process.exitCode = 1; });
