"use strict";
const assert = require("node:assert/strict"), fs = require("node:fs"), path = require("node:path"), test = require("node:test"), vm = require("node:vm");
const root = path.resolve(__dirname, "..", ".."), html = fs.readFileSync(path.join(root, "index.html"), "utf8"), clientSource = fs.readFileSync(path.join(root, "edu2gBetaClient.js"), "utf8");
function clientHarness({ fetchImpl, hostname = "localhost", search = "?auth-emulator=1", visualReview = false } = {}) { const location = { hostname, search }, window = { AIWaysAppCheck: { initializeAIWaysAppCheck: async () => ({ app: { options: { projectId: "ai-ways-incheon" } } }) }, AIWaysBetaAuth: { visualReviewRequested: () => visualReview, getEdu2gProtectedHeaders: async ({ forceRefresh } = {}) => ({ "X-Firebase-AppCheck": "app-check", Authorization: `Bearer token-${forceRefresh ? "fresh" : "cached"}` }) } }; vm.runInNewContext(clientSource, { window, location, navigator: { platform: "Win32" }, URLSearchParams, AbortController, fetch: fetchImpl, setTimeout, clearTimeout }, { filename: "edu2gBetaClient.js" }); return window.AIWaysEdu2gClient; }
// 2026-09-02: 클로즈베타 시크릿코드 UI(edu2gBetaUi.js/edu2gBeta.css, 대표님
// 지시로 폐기)가 스크립트 순서/네비게이션을 같이 검증하던 테스트였다 -
// 그 두 파일에 대한 언급만 빼고 나머지(스크립트 로딩 순서, 네비게이션
// 7개 링크)는 그대로 유지한다.
test("Gate 2A scripts are ordered and preserve the original seven navigation links", () => { const order = ["./firebaseAppCheck.js", "./firebaseBetaAuth.js", "./edu2gBetaClient.js", "./aiRuntimeLoader.js", "./app.js"].map(value => html.indexOf(value)); assert.ok(order.every((value, index) => value >= 0 && (!index || order[index - 1] < value))); assert.equal((html.match(/<nav class="main-nav"[\s\S]*?<\/nav>/)?.[0].match(/<a href=/g) || []).length, 7); });
test("Gate 2A client allowlists protected endpoints and selects production or explicit localhost emulator URLs", async () => { const client = clientHarness({ fetchImpl: async () => ({ status: 200, json: async () => ({ ok: true }) }) }); assert.equal(await client.functionUrl("checkStudentProfile"), "http://127.0.0.1:5001/demo-aiways-incheon/asia-northeast3/checkStudentProfile"); assert.equal(await client.functionUrl("analyzeSortingImage"), "http://127.0.0.1:5001/demo-aiways-incheon/asia-northeast3/analyzeSortingImage"); await assert.rejects(() => client.functionUrl("unknownEndpoint"), /endpoint_not_allowed/); const production = clientHarness({ hostname: "example.test", search: "?auth-emulator=1", fetchImpl: async () => ({ status: 200, json: async () => ({ ok: true }) }) }); assert.equal(await production.functionUrl("saveSortingRecord"), "https://asia-northeast3-ai-ways-incheon.cloudfunctions.net/saveSortingRecord"); });

test("CB-4 protected analyze and record helpers send no client actor identifier", async () => { const requests = []; const client = clientHarness({ fetchImpl: async (_url, options) => { requests.push(JSON.parse(options.body)); return { status: 200, json: async () => ({ ok: true }) }; } }); await client.analyzeSortingImage({ requestId: "request-1" }); await client.saveSortingRecord({ status: "held" }); assert.equal(requests.length, 2); assert.equal(Object.hasOwn(requests[0], "actorId"), false); assert.equal(Object.hasOwn(requests[1], "actorId"), false); });
test("Gate 2A client sends protected JSON headers and retries a 401 once with a refreshed token", async () => { const calls = [], client = clientHarness({ fetchImpl: async (_url, options) => { calls.push(options); return calls.length === 1 ? { status: 401, json: async () => ({ ok: false, code: "auth_invalid" }) } : { status: 200, json: async () => ({ ok: true, hasProfile: false }) }; } }); const result = await client.checkStudentProfile(); assert.equal(result.ok, true); assert.equal(calls.length, 2); assert.equal(calls[0].credentials, "omit"); assert.equal(calls[0].headers["Content-Type"], "application/json"); assert.equal(calls[0].headers.Authorization, "Bearer token-cached"); assert.equal(calls[1].headers.Authorization, "Bearer token-fresh"); });
test("explicit visual review mode returns before protected headers or network", async () => { const calls = []; const client = clientHarness({ visualReview: true, fetchImpl: async () => { calls.push("fetch"); return { status: 200, json: async () => ({ ok: true }) }; } }); assert.equal((await client.checkStudentProfile()).code, "auth_invalid"); assert.equal(calls.length, 0); });
test("Gate 2A client maps malformed, network and timeout responses without exposing bodies", async () => { const malformed = clientHarness({ fetchImpl: async () => ({ status: 200, json: async () => { throw new Error("bad json"); } }) }); assert.equal((await malformed.checkStudentProfile()).code, "invalid_response"); const network = clientHarness({ fetchImpl: async () => { throw new Error("offline"); } }); assert.equal((await network.checkStudentProfile()).code, "network_error"); const timeout = clientHarness({ fetchImpl: async () => { const error = new Error("aborted"); error.name = "AbortError"; throw error; } }); assert.equal((await timeout.checkStudentProfile()).code, "request_timeout"); });
test("client never logs or exposes actor/token identifiers to the console or storage", () => { assert.doesNotMatch(clientSource, /console\.|localStorage|sessionStorage|innerHTML|actorId|\.uid|idToken|edu2g-pass|redeemPass/); });
