"use strict";

const fs = require("node:fs");
const http = require("node:http");
const path = require("node:path");
const WebSocket = require("ws");
const targetUrl = "http://127.0.0.1:8001/";
const captureDir = process.env.AIWAYS_CAPTURE_DIR || "";
const viewports = [[360,800],[390,844],[768,1024],[1024,768],[1366,768],[1920,1080]];
const delay = (milliseconds) => new Promise((resolve) => setTimeout(resolve, milliseconds));
function request(pathname, method = "GET") { return new Promise((resolve, reject) => { const request = http.request({ hostname: "127.0.0.1", port: 9239, path: pathname, method }, (response) => { let body = ""; response.on("data", (chunk) => body += chunk); response.on("end", () => resolve(JSON.parse(body))); }); request.on("error", reject); request.end(); }); }
function connect(url) { return new Promise((resolve, reject) => { const socket = new WebSocket(url); let id = 0; const pending = new Map(); const events = []; socket.on("open", () => resolve({ events, send(method, params = {}) { return new Promise((done, fail) => { const messageId = ++id; pending.set(messageId, { done, fail }); socket.send(JSON.stringify({ id: messageId, method, params })); }); }, close: () => socket.close() })); socket.on("message", (message) => { const packet = JSON.parse(message); if (packet.id && pending.has(packet.id)) { const item = pending.get(packet.id); pending.delete(packet.id); return packet.error ? item.fail(packet.error) : item.done(packet.result); } if (["Runtime.exceptionThrown","Log.entryAdded"].includes(packet.method)) events.push(packet); }); socket.on("error", reject); }); }
async function evaluate(page, expression) { return (await page.send("Runtime.evaluate", { expression, returnByValue: true, awaitPromise: true })).result.value; }
async function fixture(page, width, height) { await page.send("Emulation.setDeviceMetricsOverride", { width, height, deviceScaleFactor: 1, mobile: width <= 430 }); await page.send("Page.navigate", { url: targetUrl }); await delay(220); return evaluate(page, `(() => { const result = document.querySelector('[data-sorting-result]'); const holds = document.querySelector('#holdList'); const modal = document.querySelector('#aiModal'); if (!result || !holds || !modal) return { ready:false }; result.innerHTML = '<header class="judgement-result-head"><p>AI가 확인할 항목을 제안합니다.</p><span>최종 배출 판단은 사용자가 결정합니다.</span></header><section class="judgement-details judgement-candidate-block"><strong>AI 사진 분석 참고 후보</strong><div class="judgement-chip-row">' + Array.from({length:6}, (_,i)=>'<span class="judgement-chip">후보 '+(i+1)+'</span>').join('') + '</div></section><section class="judgement-checklist"><button class="judgement-check">사용자 확인</button></section><section class="judgement-recommendation is-ready">잘했어요. 배출 준비가 완료됐습니다.</section><section class="judgement-recommendation is-hold">지금 확정하지 않아도 됩니다. 확인이 필요한 물건으로 보류함에 저장할까요?</section><p class="save-state is-error error-state">분석 오류</p>'; holds.innerHTML = Array.from({length:9},(_,i)=>'<li>보류 기록 '+(i+1)+'</li>').join(''); const visible=node=>{const style=getComputedStyle(node),box=node.getBoundingClientRect();return style.display!=="none"&&style.visibility!=="hidden"&&box.width>0&&box.height>0;}; const primary=[...document.querySelectorAll('.mobile-shell-primary,.primary-btn')].find(visible); primary?.focus(); const focus=primary?getComputedStyle(primary).outlineStyle:"none"; modal.showModal(); const close=document.querySelector('[data-close-analysis]'); const closeRect=close.getBoundingClientRect(); close.click(); const rect=(selector)=>{const b=document.querySelector(selector)?.getBoundingClientRect();return b&&{left:b.left,right:b.right,top:b.top,bottom:b.bottom,width:b.width,height:b.height}}; const ai=rect('.judgement-candidate-block'), user=rect('.judgement-checklist'), ready=rect('.is-ready'), hold=rect('.is-hold'), error=rect('.error-state'); return { ready:true, overflow:document.documentElement.scrollWidth===document.documentElement.clientWidth && document.body.scrollWidth===document.documentElement.clientWidth, clipped:[...result.querySelectorAll('p,button,strong,span')].filter(n=>visible(n)&&(n.scrollWidth>n.clientWidth+1||n.scrollHeight>n.clientHeight+1)).length, focus, modalClosed:!modal.open, close:{width:closeRect.width,height:closeRect.height}, ai,user,ready,hold,error, styles:[ai,user,ready,hold,error].map((_,i)=>getComputedStyle(document.querySelector(['.judgement-candidate-block','.judgement-checklist','.is-ready','.is-hold','.error-state'][i])).backgroundColor) }; })()`); }
(async () => { const target = await request(`/json/new?${encodeURIComponent(targetUrl)}`, "PUT"); const page = await connect(target.webSocketDebuggerUrl); await page.send("Page.enable"); await page.send("Runtime.enable"); await page.send("Log.enable"); const rows=[]; for (const [width,height] of viewports) { const row=await fixture(page,width,height); rows.push({width,height,...row}); if(captureDir){ const image=await page.send("Page.captureScreenshot",{format:"png"}); fs.mkdirSync(captureDir,{recursive:true}); fs.writeFileSync(path.join(captureDir,`${width}x${height}-states.png`),Buffer.from(image.data,"base64")); } } await page.send("Emulation.setEmulatedMedia",{features:[{name:"prefers-reduced-motion",value:"reduce"}]}); const reduced=await evaluate(page,"getComputedStyle(document.querySelector('.primary-btn')).transitionDuration"); page.close(); const failed=rows.find(row=>!row.ready||!row.overflow||row.clipped||row.focus==='none'||!row.modalClosed||row.close.width<40||row.close.height<40||!row.ai||!row.user||row.ai.bottom>row.user.top||new Set(row.styles).size<4); if(failed) throw new Error(`visual state failed: ${JSON.stringify(failed)}`); if(page.events.length) throw new Error(`console errors: ${page.events.length}`); if(!/^0(?:ms|s)|0\.001s$/.test(reduced)) throw new Error(`reduced motion failed: ${reduced}`); process.stdout.write(`${JSON.stringify({checked:rows.length,states:["default","preview","loading","candidates","uncertain","user-selection","checklist","complete","hold","error","network","records","modal","reduced-motion"],captureDir:captureDir||null})}\n`); })().catch(error=>{process.stderr.write(`${error.message}\n`);process.exitCode=1;});
