"use strict";

const fs = require("node:fs");
const http = require("node:http");
const path = require("node:path");
const WebSocket = require("ws");
const baseUrl = process.env.AIWAYS_BASE_URL || "http://127.0.0.1:8001/";
const captureDir = process.env.AIWAYS_CAPTURE_DIR || "";
const captureOnly = process.env.AIWAYS_CAPTURE_ONLY === "1";
const viewports = [[320,568],[360,800],[390,844],[412,915],[768,1024],[820,1180],[1024,768],[1280,720],[1366,768],[1440,900],[1920,1080]];
const captureWidths = new Set([390,768,1024,1366,1920]);
const sections = ["dashboard","project","curriculum","hah","flow","gallery","sorting","resources"];
const delay = (milliseconds) => new Promise((resolve) => setTimeout(resolve, milliseconds));
function request(pathname, method = "GET") { return new Promise((resolve, reject) => { const request = http.request({ hostname: "127.0.0.1", port: 9239, path: pathname, method }, (response) => { let body = ""; response.on("data", (chunk) => body += chunk); response.on("end", () => resolve(JSON.parse(body))); }); request.on("error", reject); request.end(); }); }
function connect(url) { return new Promise((resolve, reject) => { const socket = new WebSocket(url); let id = 0; const pending = new Map(); const events = []; socket.on("open", () => resolve({ events, send(method, params = {}) { return new Promise((done, fail) => { const messageId = ++id; pending.set(messageId, { done, fail }); socket.send(JSON.stringify({ id: messageId, method, params })); }); }, close: () => socket.close() })); socket.on("message", (message) => { const packet = JSON.parse(message); if (packet.id && pending.has(packet.id)) { const pendingItem = pending.get(packet.id); pending.delete(packet.id); return packet.error ? pendingItem.fail(packet.error) : pendingItem.done(packet.result); } if (["Runtime.exceptionThrown", "Log.entryAdded"].includes(packet.method)) events.push(packet); }); socket.on("error", reject); }); }
async function evaluate(page, expression) { return (await page.send("Runtime.evaluate", { expression, returnByValue: true, awaitPromise: true })).result.value; }
async function inspect(page, width, height) { await page.send("Emulation.setDeviceMetricsOverride", { width, height, deviceScaleFactor: 1, mobile: width <= 430 }); await page.send("Page.navigate", { url: baseUrl }); await delay(250); return evaluate(page, `(() => {
  const ids = ${JSON.stringify(sections)}; const rect = (node) => { const box = node?.getBoundingClientRect(); return box && { left: Math.round(box.left), top: Math.round(box.top), right: Math.round(box.right), bottom: Math.round(box.bottom), width: Math.round(box.width), height: Math.round(box.height) }; };
  const textNodes = [...document.querySelectorAll('h1,h2,h3,h4,p,button,a,label,summary')]; const clipped = textNodes.filter(node => { const style = getComputedStyle(node); const isClipped = node.scrollWidth > node.clientWidth + 1 || node.scrollHeight > node.clientHeight + 1; return isClipped && ![style.overflow, style.overflowX, style.overflowY].every(value => value === 'visible'); }).map(node => node.tagName);
  const cards = [...document.querySelectorAll('.panel,.project-cards article,.hah-grid article,.flow-grid article,.gallery-grid article,.resource-grid a')]; const outOfBounds = cards.filter(node => { const box = node.getBoundingClientRect(); return box.left < -1 || box.right > document.documentElement.clientWidth + 1; }).length;
  const buttons = [...document.querySelectorAll('button')]; const shortButtons = buttons.filter(node => { const box = node.getBoundingClientRect(); return box.width > 0 && box.height > 0 && box.height < 40; }).length;
  document.querySelector('[data-sorting-mode="search"]')?.click(); const dashboard = document.querySelector('#dashboard'); const hero = document.querySelector('#dashboard .hero-copy'); const grid = document.querySelector('#dashboard .dashboard-grid'); const search = document.querySelector('#searchInput'); const searchButton = document.querySelector('#searchButton'); const sameRowDelta = (first, second) => { const a = rect(first); const b = rect(second); return a && b && a.right <= b.left ? Math.abs(a.top - b.top) : 0; }; const sectionLefts = ids.map(id => rect(document.getElementById(id))?.left).filter(Number.isFinite); const modal = document.querySelector('#aiModal'); modal?.showModal?.(); const close = document.querySelector('[data-close-analysis]'); const closeRect = rect(close); close?.click();
  return { order: ids.map(id => document.getElementById(id)).filter(Boolean).map(node => node.id), html: document.documentElement.scrollWidth, body: document.body.scrollWidth, client: document.documentElement.clientWidth, clipped, outOfBounds, shortButtons, hero: rect(hero), grid: rect(grid), dashboard: rect(dashboard), search: rect(search), searchButton: rect(searchButton), rowTopDelta: Math.max(sameRowDelta(document.querySelector('.school-panel'), document.querySelector('.landfill-panel')), sameRowDelta(document.querySelector('.project-cards article'), document.querySelectorAll('.project-cards article')[1])), sectionLeftSpread: Math.max(...sectionLefts) - Math.min(...sectionLefts), close: closeRect, modalClosed: !modal?.open, footer: rect(document.querySelector('.footer-credit')), initialRuntimeScripts: [...document.scripts].filter(script => /tensorflow|mobilenet|teachable/i.test(script.src)).length };
})()`); }
async function capture(page, width, height, id) { if (!captureDir || !captureWidths.has(width)) return; await page.send("Page.navigate", { url: `${baseUrl}#${id}` }); await delay(160); const shot = await page.send("Page.captureScreenshot", { format: "png", captureBeyondViewport: false }); const file = path.join(captureDir, `${width}x${height}-${id}.png`); fs.mkdirSync(captureDir, { recursive: true }); fs.writeFileSync(file, Buffer.from(shot.data, "base64")); }
(async () => { const target = await request(`/json/new?${encodeURIComponent(baseUrl)}`, "PUT"); const page = await connect(target.webSocketDebuggerUrl); await page.send("Page.enable"); await page.send("Runtime.enable"); await page.send("Log.enable"); const rows = []; for (const [width, height] of viewports) { const row = await inspect(page, width, height); rows.push({ width, height, ...row }); for (const id of sections) await capture(page, width, height, id); } page.close(); if (captureOnly) return process.stdout.write(`${JSON.stringify({ captured: rows.length, captureDir })}\n`); const failed = rows.find((row) => row.order.join(",") !== sections.join(",") || row.html !== row.client || row.body !== row.client || row.clipped.length || row.outOfBounds || row.shortButtons || row.initialRuntimeScripts || row.rowTopDelta > 3 || row.sectionLeftSpread > 1 || !row.modalClosed || !row.close || row.close.width < 40 || row.close.height < 40 || !row.footer || row.footer.left < -1 || row.footer.right > row.client + 1 || (row.client >= 1024 && !(row.hero.right <= row.grid.left && row.hero.top < row.grid.bottom)) || (row.client < 1024 && !(row.hero.bottom <= row.grid.top + 1)) || !row.search || !row.searchButton || Math.abs((row.search.top + row.search.height / 2) - (row.searchButton.top + row.searchButton.height / 2)) > 3); if (failed) throw new Error(`visual alignment failed: ${JSON.stringify(failed)}`); if (page.events?.length) throw new Error(`console or runtime errors: ${page.events.length}`); process.stdout.write(`${JSON.stringify({ checked: rows.length, captureDir: captureDir || null, maxRowTopDelta: Math.max(...rows.map(row => row.rowTopDelta)), maxSectionLeftSpread: Math.max(...rows.map(row => row.sectionLeftSpread)), consoleErrors: page.events.length })}\n`); })().catch((error) => { process.stderr.write(`${error.message}\n`); process.exitCode = 1; });
