"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
const {RATE_LIMIT_SCHEMA,RATE_LIMITS,ACTOR_RATE_LIMITS,READS_PER_REQUEST_WORST_CASE,getUtcBuckets,getRetryAfterSeconds,createGlobalRateLimiter,createActorRateLimiter,hashRateLimitScope}=require("../lib/globalRateLimit");
const {createAnalyzeSortingHandler}=require("../lib/sortingVision");
function memoryDb(){const docs=new Map();let reads=0;return{docs,reads:()=>reads,collection:n=>({doc:id=>({key:`${n}/${id}`,async get(){reads++;return {exists:docs.has(`${n}/${id}`),data:()=>docs.get(`${n}/${id}`)};}})}),runTransaction:async f=>f({get:async r=>{reads++;return {exists:docs.has(r.key),data:()=>docs.get(r.key)};},set:(r,v)=>docs.set(r.key,{...(docs.get(r.key)||{}),...v})})};}
test("a low-volume function (no shards configured) costs exactly 1 read per check, same as before sharding existed",async()=>{const now=new Date("2026-07-28T23:59:59.500Z"),db=memoryDb(),limiter=createGlobalRateLimiter({db,now:()=>now,serverTimestamp:()=>"SERVER"});assert.equal(RATE_LIMITS.analyzeSortingImage.shards,undefined,"this function should not opt into sharding");await limiter.check("analyzeSortingImage");assert.equal(db.reads(),1,"2026-08-27 regression check: uniform 8-way sharding once cost 9 reads per request on every one of the 14 endpoints, not just the one that needed it");const onlyKey=[...db.docs.keys()].filter(k=>k.startsWith("system_rate_limits/analyzeSortingImage-20260728-"));assert.deepEqual(onlyKey,["system_rate_limits/analyzeSortingImage-20260728-0"]);});
test("getSchoolDashboard (the only contention-risk function) shards writes across documents but enforces the UTC limit on their sum",async()=>{let now=new Date("2026-07-28T23:59:59.500Z");const db=memoryDb(),limiter=createGlobalRateLimiter({db,now:()=>now,serverTimestamp:()=>"SERVER"});assert.deepEqual(getUtcBuckets(now),{utcDate:"20260728",minuteKey:"2359"});assert.equal(getRetryAfterSeconds(now,"minute_limited"),1);assert.equal(RATE_LIMITS.getSchoolDashboard.shards,8);const perMinute=RATE_LIMITS.getSchoolDashboard.perMinute;for(let i=0;i<perMinute;i++)assert.equal((await limiter.check("getSchoolDashboard")).allowed,true);assert.equal((await limiter.check("getSchoolDashboard")).outcome,"minute_limited");const shardKeys=[...db.docs.keys()].filter(k=>k.startsWith("system_rate_limits/getSchoolDashboard-20260728-"));assert.ok(shardKeys.length>=1,"expected at least one shard document");let summedTotal=0;for(const key of shardKeys){const doc=db.docs.get(key);assert.equal(doc.schemaVersion,RATE_LIMIT_SCHEMA);summedTotal+=doc.totalCount;}assert.equal(summedTotal,perMinute);});
test("actor limits are isolated and their document ids do not disclose actor scope",async()=>{const db=memoryDb(),limiter=createActorRateLimiter({db,now:()=>new Date("2026-07-28T12:00:00Z"),limits:{saveSortingRecord:{perMinute:1}}});assert.equal((await limiter.check("saveSortingRecord","actor_a")).allowed,true);assert.equal((await limiter.check("saveSortingRecord","actor_a")).outcome,"minute_limited");assert.equal((await limiter.check("saveSortingRecord","actor_b")).allowed,true);for(const key of db.docs.keys()){assert.equal(key.includes("actor_a"),false);assert.equal(key.includes("actor_b"),false);}assert.equal(hashRateLimitScope("actor_a").length,64);});
test("2026-08-29 (100점 목표 4번) worst-case daily READS - not requests - for the two multi-read functions stay at their documented, reviewed values; a perDay bump must consciously update this too",()=>{
  const dashboardWorstCaseReadsPerDay=RATE_LIMITS.getSchoolDashboard.perDay*READS_PER_REQUEST_WORST_CASE.getSchoolDashboard;
  const rankingWorstCaseReadsPerDay=RATE_LIMITS.getClassRanking.perDay*READS_PER_REQUEST_WORST_CASE.getClassRanking;
  assert.equal(dashboardWorstCaseReadsPerDay,2000000,"getSchoolDashboard perDay(500000) x worst-case reads/request(4) changed - re-review the cost budget before adjusting this number");
  assert.equal(rankingWorstCaseReadsPerDay,10000,"getClassRanking perDay(5000) x worst-case reads/request(2) changed - re-review the cost budget before adjusting this number");
});
test("2026-08-29 (cost review): analyzeSortingSafetyObserver has a per-actor cap - a single actor cannot alone exhaust the function's whole global daily budget",()=>{
  assert.ok(ACTOR_RATE_LIMITS.analyzeSortingSafetyObserver,"analyzeSortingSafetyObserver must have an ACTOR_RATE_LIMITS entry - without one, createActorRateLimiter.check() returns allowed:true unconditionally (see globalRateLimit.js ~line 194), and this function is directly client-callable (edu2gBetaClient.js ALLOWED list), so one actor could consume the entire global perDay budget alone");
  assert.ok(ACTOR_RATE_LIMITS.analyzeSortingSafetyObserver.perDay<RATE_LIMITS.analyzeSortingSafetyObserver.perDay,"the per-actor cap should be meaningfully below the shared global cap");
});
test("rate rejections stop analysis before provider",async()=>{let provider=0;const handler=createAnalyzeSortingHandler({appCheck:async()=>({status:"valid"}),access:{resolve:async()=>({ok:true,actorId:"actor_test"})},rateLimiter:{check:async()=>({allowed:false,outcome:"minute_limited",retryAfterSeconds:9})},actorRateLimiter:{check:async()=>({allowed:true})},analysisRequests:{claimAnalysisRequest:async()=>({state:"claimed"})},getApiKey:()=>"mock",createClient:()=>({models:{generateContent:async()=>{provider++;}}})});const out={};await handler({method:"POST",headers:{},body:{}},{set(){return this},status(s){out.status=s;return this},json(b){out.body=b;return this}});assert.equal(out.status,429);assert.equal(provider,0);});
