"use strict";
// Auth/Firestore Emulator only: real anonymous ID tokens and real binding documents.
const assert=require("node:assert/strict"),http=require("node:http");
const {initializeApp,getApps}=require("firebase-admin/app"); const {getAuth}=require("firebase-admin/auth"); const {getFirestore,FieldValue}=require("firebase-admin/firestore");
const {createEdu2gDeviceAccess}=require("../lib/edu2gDeviceAccess"); const {createAnalysisIdempotency}=require("../lib/analysisIdempotency");
const projectId=process.env.GCLOUD_PROJECT||"demo-aiways-incheon";
function signup(){return new Promise((resolve,reject)=>{const req=http.request({hostname:"127.0.0.1",port:9099,path:"/identitytoolkit.googleapis.com/v1/accounts:signUp?key=fake-api-key",method:"POST",headers:{"Content-Type":"application/json"}},res=>{let data="";res.on("data",c=>data+=c);res.on("end",()=>resolve(JSON.parse(data)));});req.on("error",reject);req.end(JSON.stringify({returnSecureToken:true}));});}
(async()=>{const app=getApps()[0]||initializeApp({projectId}),auth=getAuth(app),db=getFirestore(app),access=createEdu2gDeviceAccess({auth,db,serverTimestamp:()=>FieldValue.serverTimestamp()}),requests=createAnalysisIdempotency({db,serverTimestamp:()=>FieldValue.serverTimestamp(),model:"test"});const users=[];try{for(let i=0;i<4;i++){const signed=await signup(),decoded=await auth.verifyIdToken(signed.idToken);users.push({token:signed.idToken,uid:decoded.uid});}for(const [i,actorId] of [[0,"actor_a"],[1,"actor_a"],[2,"actor_b"],[3,"actor_b"]]){const user=users[i],actor=db.collection("actors").doc(actorId);await actor.set({status:"active",plan:"closed_beta"});await actor.collection("trustedDevices").doc(user.uid).set({uid:user.uid,status:"active",managementId:"123e4567-e89b-42d3-a456-42661417400"+(i+1)});await db.collection("edu2gDeviceBindings").doc(user.uid).set({actorId,status:"active"});}
const req=i=>({headers:{authorization:`Bearer ${users[i].token}`}});assert.equal((await access.resolve(req(0))).actorId,"actor_a");assert.equal((await access.resolve(req(1))).actorId,"actor_a");assert.equal((await access.resolve(req(2))).actorId,"actor_b");assert.equal((await access.resolve({headers:{}})).code,"auth_missing");await db.collection("edu2gDeviceBindings").doc(users[3].uid).delete();assert.equal((await access.resolve(req(3))).code,"device_not_registered");await db.collection("edu2gDeviceBindings").doc(users[1].uid).update({status:"revoked"});assert.equal((await access.resolve(req(1))).code,"device_revoked");const key="123e4567-e89b-42d3-a456-426614174000";assert.equal((await requests.claimAnalysisRequest("actor_a",key)).state,"claimed");assert.equal((await requests.claimAnalysisRequest("actor_b",key)).state,"claimed");await requests.completeAnalysisRequest("actor_a",key,{safe:true});const b=await requests.claimAnalysisRequest("actor_b",key);assert.notEqual(b.state,"completed");const docs=await db.collection("system_analysis_requests").get();for(const doc of docs.docs){const serialized=JSON.stringify(doc.data());assert.equal(serialized.includes(key),false);assert.equal(serialized.includes(users[0].token),false);}process.stdout.write(JSON.stringify({protectedActorEmulatorIntegration:"passed",actors:2,devices:4})+"\n");}finally{const batch=db.batch();for(const user of users){batch.delete(db.collection("edu2gDeviceBindings").doc(user.uid));}for(const actorId of ["actor_a","actor_b"]){const devices=await db.collection("actors").doc(actorId).collection("trustedDevices").get();devices.docs.forEach(d=>batch.delete(d.ref));batch.delete(db.collection("actors").doc(actorId));}const claims=await db.collection("system_analysis_requests").get();claims.docs.forEach(d=>batch.delete(d.ref));await batch.commit();}})().catch(e=>{process.stderr.write(`${e.message}\n`);process.exitCode=1;});
