"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
const {createSortingLocalStore,buildSortingRecordsCsv}=require("../../sortingLocalStore.js");
const adapter=()=>{const rows=new Map();return {async get(k){return rows.get(k)||null},async put(v){rows.set(v.clientRecordId,{...v});return v},async all(){return [...rows.values()]},async del(k){rows.delete(k)},async clear(){rows.clear()}}};
test("local store whitelists the record schema and preserves idempotent identity",async()=>{const store=createSortingLocalStore(adapter());const first=await store.saveLocalSortingRecord({clientRecordId:"r1",createdAt:"2026-08-07T00:00:00.000Z",decision:"completed",category:"plastic",imageBase64:"no",token:"no"});const second=await store.saveLocalSortingRecord({clientRecordId:"r1",decision:"completed",syncStatus:"pending",actorId:"no"});assert.equal(first.createdAt,second.createdAt);assert.equal(second.clientRecordId,"r1");assert.equal("imageBase64" in second,false);assert.equal("token" in second,false);assert.equal("actorId" in second,false)});
test("pending sync continues after a failed record and records a safe error code",async()=>{const store=createSortingLocalStore(adapter());await store.saveLocalSortingRecord({clientRecordId:"bad",decision:"completed"});await store.saveLocalSortingRecord({clientRecordId:"good",decision:"completed"});const results=await store.syncPendingSortingRecords(async record=>{if(record.clientRecordId==="bad"){const error=new Error("forbidden");error.status=403;throw error}return {serverRecordId:"server-good"}});assert.equal(results.length,2);assert.equal((await store.getLocalSortingRecord("bad")).syncStatus,"failed");assert.equal((await store.getLocalSortingRecord("bad")).lastSyncErrorCode,"app-check-permission-denied");assert.equal((await store.getLocalSortingRecord("good")).syncStatus,"synced")});
test("held records resolve in place and recover through another store instance",async()=>{const shared=adapter(),first=createSortingLocalStore(shared);await first.saveLocalSortingRecord({clientRecordId:"held-1",decision:"held",status:"held",syncStatus:"synced"});const resolved=await first.resolveLocalHeldRecord("held-1",{displayLabel:"resolved"});const second=createSortingLocalStore(shared);assert.equal(resolved.clientRecordId,"held-1");assert.equal(resolved.status,"resolved");assert.equal(resolved.syncStatus,"pending");assert.equal((await second.listLocalSortingRecords()).length,1)});
test("CSV is deterministic, spreadsheet-safe, and excludes sensitive fields",()=>{const csv=buildSortingRecordsCsv([{clientRecordId:"r2",createdAt:"2026-08-07T00:00:01.000Z",decision:"completed",status:"completed",displayLabel:"=formula",token:"secret"},{clientRecordId:"r2",createdAt:"2026-08-07T00:00:01.000Z",decision:"completed",status:"completed"}]);assert.ok(csv.startsWith("\uFEFFclientRecordId,"));assert.match(csv,/\"'=formula\"/);assert.equal((csv.match(/\r\n/g)||[]).length,1);assert.equal(csv.includes("secret"),false)});
test("storage failures propagate without a false success",async()=>{const failing={...adapter(),async put(){throw new Error("quota")}},store=createSortingLocalStore(failing);await assert.rejects(store.saveLocalSortingRecord({clientRecordId:"x"}),/quota/)});
