"use strict";
const { SCHEMA_VERSION } = require("./sortingRecord");
const MAX_BODY = 12 * 1024;
const ACTOR = "emulator-test-actor";
function send(res, code, body) { return res.status(code).json(body); }
function origin(req, res) { const value = String(req.headers?.origin || ""); if (value && !/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/.test(value)) return false; if (value) { res.set("Access-Control-Allow-Origin", value); res.set("Access-Control-Allow-Methods", "POST, OPTIONS"); res.set("Access-Control-Allow-Headers", "Content-Type"); } return true; }
function validKey(value) { return typeof value === "string" && /^[A-Za-z0-9_-]{16,80}$/.test(value); }
function timestamp(value) { return value?.toDate ? value.toDate().toISOString() : (value instanceof Date ? value.toISOString() : value || null); }
function publicRecord(id, data) { const out = { recordId: id }; for (const key of ["schemaVersion","status","provider","model","analysis","checklist","userDecision","hold","resolutionType","appVersion","sourceSchemaVersion"]) if (data[key] !== undefined) out[key] = data[key]; for (const key of ["createdAt","updatedAt","expireAt","resolvedAt"]) if (data[key] !== undefined) out[key] = timestamp(data[key]); return out; }
function guard(req, res) { if (!origin(req,res)) return false; if (req.method === "OPTIONS") { res.status(204).send(""); return false; } if (req.method !== "POST") { send(res,405,{ok:false,code:"method_not_allowed"}); return false; } if ((req.rawBody?.length || Buffer.byteLength(JSON.stringify(req.body||{}))) > MAX_BODY) { send(res,413,{ok:false,code:"request_too_large"}); return false; } if (req.headers?.["content-type"] && !String(req.headers["content-type"]).includes("application/json")) { send(res,415,{ok:false,code:"invalid_content_type"}); return false; } return true; }
async function applyLimit(res, limiter, functionName) { const limit=await limiter.check(functionName); if(limit.allowed)return true; if(limit.outcome==="unavailable"){send(res,503,{ok:false,code:"protection_unavailable"});return false;} res.set("Retry-After",String(limit.retryAfterSeconds));send(res,429,{ok:false,code:"rate_limit_exceeded",retryAfterSeconds:limit.retryAfterSeconds});return false; }
function createListSortingRecordsHandler({ store, allowTestActor = false, rateLimiter = { check: async () => ({ allowed: false, outcome: "unavailable" }) } }) { return async (req,res) => { if (!guard(req,res)) return; const b=req.body||{}; if (Object.keys(b).some(k=>!["actorId","pageSize","cursor","statusFilter"].includes(k)) || !allowTestActor || b.actorId !== ACTOR) return send(res,503,{ok:false,code:"actor_not_resolved"}); const size=b.pageSize===undefined?20:Number(b.pageSize); if (!Number.isInteger(size)||size<1||size>40||!['all','completed','held'].includes(b.statusFilter||'all') || (b.cursor && !validKey(b.cursor))) return send(res,400,{ok:false,code:"invalid_request"}); if(!await applyLimit(res,rateLimiter,"listSortingRecords"))return; const page=await store.list(ACTOR,size,b.cursor||"",b.statusFilter||"all"); return send(res,200,{records:page.records.map(r=>publicRecord(r.id,r.data)),nextCursor:page.nextCursor||null,hasMore:!!page.nextCursor,schemaVersion:SCHEMA_VERSION}); }; }
function createResolveSortingRecordHandler({ store, allowTestActor = false, serverTimestamp, rateLimiter = { check: async () => ({ allowed: false, outcome: "unavailable" }) } }) { return async (req,res) => { if (!guard(req,res)) return; const b=req.body||{}; if (Object.keys(b).some(k=>!["actorId","recordId","idempotencyKey","resolutionType","userDecision","checklist"].includes(k)) || !allowTestActor || b.actorId!==ACTOR) return send(res,503,{ok:false,code:"actor_not_resolved"}); if (!validKey(b.recordId)||!validKey(b.idempotencyKey)||!["confirmed_after_review","corrected_after_review"].includes(b.resolutionType)||!b.userDecision?.userConfirmed||!Array.isArray(b.checklist)||b.checklist.some(x=>!x?.checked)) return send(res,400,{ok:false,code:"invalid_resolution"}); if(!await applyLimit(res,rateLimiter,"resolveSortingRecord"))return; const result=await store.resolve(ACTOR,b,serverTimestamp()); return send(res,result.code=== "not_found"?404:result.code==="conflict"?409:200,result); }; }
module.exports={createListSortingRecordsHandler,createResolveSortingRecordHandler,publicRecord};
